version: '3'
services:
  proxy:
    image: "traefik:latest"
    ports:
      - "8090:8080"
      - "8081:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    network_mode: bridge

